const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const main = fs.readFileSync(path.join(root, 'src', 'main.js'), 'utf8');
const preload = fs.readFileSync(path.join(root, 'src', 'preload.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'src', 'renderer', 'index.html'), 'utf8');
assert.equal(pkg.build.asar.disableIntegrity, false);
assert.equal(pkg.build.electronFuses.enableEmbeddedAsarIntegrityValidation, true);
assert.equal(pkg.build.electronFuses.onlyLoadAppFromAsar, true);
assert.equal(pkg.build.electronFuses.runAsNode, false);
assert.equal(pkg.build.electronFuses.enableNodeOptionsEnvironmentVariable, false);
assert.equal(pkg.build.electronFuses.enableNodeCliInspectArguments, false);
assert(main.includes('contextIsolation: true'));
assert(main.includes('nodeIntegration: false'));
assert(main.includes('sandbox: true'));
assert(main.includes('webviewTag: false'));
assert(main.includes("setPermissionRequestHandler"));
assert(main.includes("setWindowOpenHandler"));
assert(main.includes('assertTrustedSender(event)'));
assert(preload.includes('contextBridge.exposeInMainWorld'));
assert(html.includes('Content-Security-Policy'));
console.log('ALFASTEC security hardening check: PASS');
